# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

category1 = Category.create(name: '応用知識経験', root: true)
category2 = Category.create(name: '基礎知識技術', root: true)
category3 = Category.create(name: '- ', root: true)
category4 = Category.create(name: '-')
category5 = Category.create(name: 'object detection')
category6 = Category.create(name: '生き物')
category7 = Category.create(name: '生体検知')
category8 = Category.create(name: '車')
category9 = Category.create(name: '種類')
category10 = Category.create(name: 'ナンバー')
category11 = Category.create(name: 'AR')
category12 = Category.create(name: '符号')
category13 = Category.create(name: '文書')
category14 = Category.create(name: '手書き')
category15 = Category.create(name: '印刷')
category16 = Category.create(name: '証明書認識')
category17 = Category.create(name: '名札認識')
category18 = Category.create(name: 'カード認識')
category19 = Category.create(name: '人')
category20 = Category.create(name: '体')
category21 = Category.create(name: '人検知')
category22 = Category.create(name: '手まね')
category23 = Category.create(name: '姿勢')
category24 = Category.create(name: '顔')
category25 = Category.create(name: '顔認識')
category26 = Category.create(name: 'キーポイント照合')
category27 = Category.create(name: '人種分類')
category28 = Category.create(name: '聴覚')
category29 = Category.create(name: '音認識')
category30 = Category.create(name: '声認識')
category31 = Category.create(name: '音声-文書互換')
category32 = Category.create(name: '翻訳')
category33 = Category.create(name: '歌認識')
category34 = Category.create(name: '総合判定')
category35 = Category.create(name: '運転')
category36 = Category.create(name: '四輪車')
category37 = Category.create(name: '電車')
category38 = Category.create(name: '予測')
category39 = Category.create(name: '株')
category40 = Category.create(name: '棋')
category41 = Category.create(name: 'ゲームAI')
category42 = Category.create(name: '自然言語処理')
category43 = Category.create(name: '交互AI')
category44 = Category.create(name: '数学')
category45 = Category.create(name: '確立と統計')
category46 = Category.create(name: '正規分布')
category47 = Category.create(name: 'ランダム分布')
category48 = Category.create(name: 'ベイズ推定')
category49 = Category.create(name: '最尤推定')
category50 = Category.create(name: '線形代数全般')
category51 = Category.create(name: '解析全般')
category52 = Category.create(name: 'プログラミング')
category53 = Category.create(name: 'C/C++')
category54 = Category.create(name: 'python')
category55 = Category.create(name: '基礎ライブラリー')
category56 = Category.create(name: 'sys,os,pickleなど基礎の基礎')
category57 = Category.create(name: 'math,numpy,scipyなど数式計算')
category58 = Category.create(name: 'JupyterNotebookなどインターフェイス')
category59 = Category.create(name: 'matplotlib,opencvなど図形処理や可視化')
category60 = Category.create(name: 'hdf5など単一の機能を持つサブライブラリー')
category61 = Category.create(name: 'ディープラーニングライブラリー')
category62 = Category.create(name: 'Tensorflow')
category63 = Category.create(name: 'Karas')
category64 = Category.create(name: 'caffee')
category65 = Category.create(name: 'MXNet')
category66 = Category.create(name: 'PyTorch')
category67 = Category.create(name: '機械学習')
category68 = Category.create(name: '特徴量エンジニア')
category69 = Category.create(name: 'データエンジニア')
category70 = Category.create(name: '特徴分析')
category71 = Category.create(name: '教師あり学習')
category72 = Category.create(name: '線形分析')
category73 = Category.create(name: '線形回帰')
category74 = Category.create(name: 'logistic回帰')
category75 = Category.create(name: '木分析アサンブル学習')
category76 = Category.create(name: 'ランダムフォレスト')
category77 = Category.create(name: 'GBDT')
category78 = Category.create(name: 'XGBoost')
category79 = Category.create(name: 'lightGBM')
category80 = Category.create(name: 'SVM')
category81 = Category.create(name: 'Navy bayes')
category82 = Category.create(name: 'HMM')
category83 = Category.create(name: 'MRF')
category84 = Category.create(name: 'CRF')
category85 = Category.create(name: '協調フィルタリング')
category86 = Category.create(name: 'FM/FFM')
category87 = Category.create(name: '教師なし学習')
category88 = Category.create(name: 'Cluster Analysis')
category89 = Category.create(name: 'dimensionality reduction')
category90 = Category.create(name: '深層学習')
category91 = Category.create(name: 'NN')
category92 = Category.create(name: 'DNN')
category93 = Category.create(name: 'CNN')
category94 = Category.create(name: 'AlexNets')
category95 = Category.create(name: 'VGGNets')
category96 = Category.create(name: 'GoogleNet')
category97 = Category.create(name: 'Inception')
category98 = Category.create(name: 'ResNets')
category99 = Category.create(name: 'MobileNets')
category100 = Category.create(name: 'RNN')
category101 = Category.create(name: 'RCNN')
category102 = Category.create(name: 'Fast RCNN')
category103 = Category.create(name: 'Mask RCNN')
category104 = Category.create(name: 'LTSM')
category105 = Category.create(name: 'GAN')
category106 = Category.create(name: 'ディープラーニング')
category107 = Category.create(name: 'パラメーター調整知識など')
category108 = Category.create(name: 'optimizer')
category109 = Category.create(name: 'SGDなど')
category110 = Category.create(name: 'loss関数')
category111 = Category.create(name: '状況に応じて作る')
category112 = Category.create(name: 'サブ関数')
category113 = Category.create(name: 'accのような機械学習に影響しない統計関数など')
category114 = Category.create(name: '運用')
category115 = Category.create(name: '右に参照')
category116 = Category.create(name: '強化学習')
category117 = Category.create(name: 'マルコフ決定過程')
category118 = Category.create(name: 'モンテカルロ・シミュレーション')
category119 = Category.create(name: '時間差分法')
category120 = Category.create(name: '価値評価法')
category121 = Category.create(name: 'DQN')
category122 = Category.create(name: 'TRPO')
category123 = Category.create(name: '転移学習')
category124 = Category.create(name: 'fine-tune')
category125 = Category.create(name: 'multi-task learning')
category126 = Category.create(name: 'zero-shot learning')

Layer.create(category1_id: category1.id, category2_id: category5.id, category3_id: category6.id, category4_id: category7.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category8.id, category4_id: category9.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category10.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category11.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category12.id, category4_id: category13.id, category5_id: category14.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category15.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category16.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category17.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category18.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category19.id, category4_id: category20.id, category5_id: category21.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category22.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category23.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category24.id, category5_id: category25.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category26.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category27.id)
Layer.create(category1_id: category3.id, category2_id: category28.id, category3_id: category29.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category30.id, category4_id: category31.id, category5_id: category32.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category33.id)
Layer.create(category1_id: category3.id, category2_id: category34.id, category3_id: category35.id, category4_id: category36.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category37.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category38.id, category4_id: category39.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category40.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category41.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category42.id, category4_id: category43.id)
Layer.create(category1_id: category2.id, category2_id: category44.id, category3_id: category45.id, category4_id: category46.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category47.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category48.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category49.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category50.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category51.id)
Layer.create(category1_id: category2.id, category2_id: category52.id, category3_id: category53.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category54.id,  category5_id: category55.id, category6_id: category56.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category57.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category58.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category59.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category60.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category61.id, category5_id: category62.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category63.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category64.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category65.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category66.id)
Layer.create(category1_id: category2.id, category2_id: category67.id, category3_id: category68.id, category4_id: category69.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category70.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category71.id, category4_id: category72.id, category5_id: category73.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category74.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category75.id, category5_id: category76.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category77.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category78.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category79.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category80.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category81.id, category5_id: category82.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category83.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category84.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category85.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category86.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category87.id, category4_id: category88.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category89.id)
Layer.create(category1_id: category3.id, category2_id: category90.id, category3_id: category91.id, category4_id: category92.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category93.id, category5_id: category94.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category95.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category96.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category97.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category98.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category99.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category100.id, category5_id: category101.id, category6_id: category102.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category4.id, category6_id: category103.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category104.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category105.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category106.id, category4_id: category107.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category108.id, category5_id: category109.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category110.id, category5_id: category111.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category112.id, category5_id: category113.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category114.id, category5_id: category115.id)
Layer.create(category1_id: category3.id, category2_id: category116.id, category3_id: category4.id, category4_id: category117.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category118.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category119.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category120.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category121.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category122.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category4.id, category4_id: category4.id, category5_id: category123.id, category6_id: category124.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category125.id)
Layer.create(category1_id: category3.id, category2_id: category4.id, category3_id: category126.id)

User.create(login: 'admin1', email: 'admin1@example.com', username: 'Admin1', password: '12345678', admin: true)
User.create(login: 'user1', email: 'user1@example.com', username: 'User1', password: '12345678', admin: false)
