# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


category1 = Category.create(name: 'OS', root: true)
category2 = Category.create(name: '言語', root: true)
category3 = Category.create(name: 'データベース', root: true)
category4 = Category.create(name: 'ネットワーク', root: true)
category5 = Category.create(name: 'ストレージ', root: true)
category6 = Category.create(name: 'Webアプリケーションサーバ', root: true)
category7 = Category.create(name: 'セキュリティ', root: true)
category8 = Category.create(name: '統合業務パッケージ', root: true)
category9 = Category.create(name: 'グループウェア', root: true)
category10 = Category.create(name: '運用管理・監視', root: true)
category11 = Category.create(name: '-', root: true)
category12 = Category.create(name: 'Solaris')
category13 = Category.create(name: 'UXP/DS')
category14 = Category.create(name: 'UNIXその他')
category15 = Category.create(name: 'Red Hat Linux')
category16 = Category.create(name: 'Turbolinux')
category17 = Category.create(name: 'Kondara/MMU Linux')
category18 = Category.create(name: 'Vine Linux')
category19 = Category.create(name: 'Debian/GNU Linux')
category20 = Category.create(name: 'Plamo Linux')
category21 = Category.create(name: 'Linuxその他')
category22 = Category.create(name: 'Windows2000 Server')
category23 = Category.create(name: 'Windows2000 Advanced Server')
category24 = Category.create(name: 'Windows2000 Datacenter Server')
category25 = Category.create(name: 'Windows2003 Server')
category26 = Category.create(name: 'WindowsXP Professional Edition')
category27 = Category.create(name: 'WindowsVISTA')
category28 = Category.create(name: 'MacOS')
category29 = Category.create(name: 'NetWare/InternetWare')
category30 = Category.create(name: 'LAN Manager')
category31 = Category.create(name: 'OS/2 Warp Server')
category32 = Category.create(name: 'サーバOSその他')
category33 = Category.create(name: 'SX/G')
category34 = Category.create(name: 'ASP')
category35 = Category.create(name: 'XSP')
category36 = Category.create(name: 'MSP')
category37 = Category.create(name: 'SXO')
category38 = Category.create(name: 'スパコンOS')
category39 = Category.create(name: '他社メインフレームOS')
category40 = Category.create(name: 'COBOL')
category41 = Category.create(name: 'PowerCOBOL')
category42 = Category.create(name: 'YPS')
category43 = Category.create(name: 'YPS/APG')
category44 = Category.create(name: 'CASET')
category45 = Category.create(name: 'PowerAE')
category46 = Category.create(name: 'NetCOBOL')
category47 = Category.create(name: 'FORTRAN')
category48 = Category.create(name: 'VPP-FORTRAN')
category49 = Category.create(name: 'C/C++')
category50 = Category.create(name: 'Visual C++')
category51 = Category.create(name: 'C#')
category52 = Category.create(name: 'Perl')
category53 = Category.create(name: 'ComponentAA/BRMODELLER')
category54 = Category.create(name: 'AA/BRMODELLER')
category55 = Category.create(name: 'Visual BASIC')
category56 = Category.create(name: 'Delphi')
category57 = Category.create(name: 'Pro*C/C++')
category58 = Category.create(name: 'Pro*COBOL')
category59 = Category.create(name: 'Java')
category60 = Category.create(name: 'JavaScript')
category61 = Category.create(name: 'VBScript')
category62 = Category.create(name: 'Java Davelopment Kit')
category63 = Category.create(name: 'Visual J++')
category64 = Category.create(name: 'VB.net')
category65 = Category.create(name: 'F-BASIC')
category66 = Category.create(name: 'ASP(Active Server Pages)')
category67 = Category.create(name: 'JSP(Java Server Pages')
category68 = Category.create(name: 'HTML')
category69 = Category.create(name: 'XML')
category70 = Category.create(name: 'PHP')
category71 = Category.create(name: 'AIM/DC')
category72 = Category.create(name: 'SQL')
category73 = Category.create(name: 'PL/SQL')
category74 = Category.create(name: 'TransactSQL')
category75 = Category.create(name: 'CA-INGRES')
category76 = Category.create(name: 'ACCELL')
category77 = Category.create(name: 'UNIFACE')
category78 = Category.create(name: 'PowerBuilder')
category79 = Category.create(name: 'Centura')
category80 = Category.create(name: 'Designer(/2000)')
category81 = Category.create(name: 'Developer(/2000)')
category82 = Category.create(name: 'APWORKS')
category83 = Category.create(name: 'JBuilder')
category84 = Category.create(name: 'SQLその他')
category85 = Category.create(name: '言語その他')
category86 = Category.create(name: 'OLTP')
category87 = Category.create(name: 'データマイニング')
category88 = Category.create(name: 'R-OLAP')
category89 = Category.create(name: 'M-OLAP')
category90 = Category.create(name: 'SymfoWARE Navigator')
category91 = Category.create(name: 'SymfoWARE Essbase')
category92 = Category.create(name: 'Business Objects')
category93 = Category.create(name: 'Red Brick Warehouse')
category94 = Category.create(name: 'Oracle OLAP Server')
category95 = Category.create(name: 'Sybase IQ')
category96 = Category.create(name: 'IBM DB2 OLAP Server')
category97 = Category.create(name: 'SymfoWARE Server')
category98 = Category.create(name: 'RDBⅡ')
category99 = Category.create(name: 'INFORMIX')
category100 = Category.create(name: 'ORACLE')
category101 = Category.create(name: 'SYBASE')
category102 = Category.create(name: 'Access')
category103 = Category.create(name: 'SQL Server')
category104 = Category.create(name: 'IBM DB2 Universal Database')
category105 = Category.create(name: 'AIM/DB(NDB,RDB')
category106 = Category.create(name: 'PowerGres Plus(PostgresSQL')
category107 = Category.create(name: 'Shunsaku')
category108 = Category.create(name: 'PostgresSQL')
category109 = Category.create(name: 'MySQL')
category110 = Category.create(name: 'BizSearch')
category111 = Category.create(name: 'TCP/IP')
category112 = Category.create(name: 'FNA')
category113 = Category.create(name: 'SNA')
category114 = Category.create(name: 'OSI')
category115 = Category.create(name: 'IPX/SPX')
category116 = Category.create(name: 'NetBEUI')
category117 = Category.create(name: 'Apple Talk')
category118 = Category.create(name: 'DECnet')
category119 = Category.create(name: 'XNS')
category120 = Category.create(name: 'HTTP')
category121 = Category.create(name: 'PPP')
category122 = Category.create(name: 'IPv6')
category123 = Category.create(name: 'VoIP(H.323,SIP')
category124 = Category.create(name: 'IPSec')
category125 = Category.create(name: 'Radius')
category126 = Category.create(name: 'LHシリーズレピータHUB')
category127 = Category.create(name: 'SHシリーズスイッチングHUB')
category128 = Category.create(name: 'SR/SBシリーズバックボーンスイッチ')
category129 = Category.create(name: 'LR/LR-Xシリーズルータ')
category130 = Category.create(name: 'SiRシリーズルータ')
category131 = Category.create(name: 'GeoStremeR900シリーズルータ')
category132 = Category.create(name: 'GeoStreamA300/500シリーズ')
category133 = Category.create(name: 'FLASHWAVE2700シリーズ')
category134 = Category.create(name: 'FLASHWAVE2300シリーズ')
category135 = Category.create(name: 'FLASHWAVE5000シリーズ')
category136 = Category.create(name: 'SiV/LR-V VoIPゲートウェイ')
category137 = Category.create(name: 'GeoServeシリーズ')
category138 = Category.create(name: 'Nethelterシリーズ')
category139 = Category.create(name: 'IPCOMシリーズ')
category140 = Category.create(name: 'IPCOM-Sシリーズ')
category141 = Category.create(name: 'FMWT/FMWBR無線LAN')
category142 = Category.create(name: 'CISCOリモートルータ(800/1700/2600シリーズ)')
category143 = Category.create(name: 'CISCOセンタールータ(3700/3600,7X00シリーズ)')
category144 = Category.create(name: 'Catalyst29XXシリーズ')
category145 = Category.create(name: 'Catalyst3000/4000シリーズ')
category146 = Category.create(name: 'Catalyst6500シリーズ')
category147 = Category.create(name: 'Aironet1100・1200シリーズ')
category148 = Category.create(name: 'BlackDiamond')
category149 = Category.create(name: 'Alpine')
category150 = Category.create(name: 'Summitシリーズ')
category151 = Category.create(name: 'SAN(Storage Area Network)技術')
category152 = Category.create(name: 'NAS(Network Attched Storage)技術')
category153 = Category.create(name: 'ETRNUS 3000/6000series')
category154 = Category.create(name: 'ETRNUS NR1000Series')
category155 = Category.create(name: 'Softek系シリーズ')
category156 = Category.create(name: 'SP5000')
category157 = Category.create(name: 'XLデータムーバ')
category158 = Category.create(name: 'Veritas Volume Manager')
category159 = Category.create(name: 'Veritas File System')
category160 = Category.create(name: '分散トランザクション')
category161 = Category.create(name: 'オンラインリアルタイム設計')
category162 = Category.create(name: 'JavaBeans')
category163 = Category.create(name: 'EJB(Enterprise JavaBeans)')
category164 = Category.create(name: 'J2EE(Java 2 Enterprise Edition)')
category165 = Category.create(name: 'CORBA')
category166 = Category.create(name: 'OLE/OLE2')
category167 = Category.create(name: 'ActiveX')
category168 = Category.create(name: 'DCOM')
category169 = Category.create(name: 'ODBC')
category170 = Category.create(name: 'JDBC')
category171 = Category.create(name: 'SOAP')
category172 = Category.create(name: 'Flash')
category173 = Category.create(name: 'Client J Framework')
category174 = Category.create(name: 'その他リッチクライアント')
category175 = Category.create(name: 'CGI')
category176 = Category.create(name: 'TUXEDO')
category177 = Category.create(name: 'PowerAIM')
category178 = Category.create(name: 'MeFt/Web')
category179 = Category.create(name: 'MeFt/TP')
category180 = Category.create(name: 'SVF for Web')
category181 = Category.create(name: 'クリスタルレポート')
category182 = Category.create(name: 'Report Director(帳票作成ソフト)')
category183 = Category.create(name: 'Universal Connect(帳票作成ソフト)')
category184 = Category.create(name: 'Interstage List Manager')
category185 = Category.create(name: 'Interstage List Works')
category186 = Category.create(name: 'Interstage List Creator')
category187 = Category.create(name: 'Interstage Form Coordinator')
category188 = Category.create(name: 'その他帳票作成ソフト')
category189 = Category.create(name: 'TPシリーズ')
category190 = Category.create(name: 'MeFtシリーズ')
category191 = Category.create(name: 'AP/JOIN')
category192 = Category.create(name: 'DB-EXPRESS')
category193 = Category.create(name: 'RDA-SV')
category194 = Category.create(name: 'SEQUELINK')
category195 = Category.create(name: 'DPCLIB')
category196 = Category.create(name: 'Linkexpress')
category197 = Category.create(name: '6680ファイル転送')
category198 = Category.create(name: 'HULFT')
category199 = Category.create(name: 'Web.SQL')
category200 = Category.create(name: 'NETSTAGE')
category201 = Category.create(name: 'IBM Connection')
category202 = Category.create(name: '連携ソフトその他')
category203 = Category.create(name: 'Interstage StandardEdition')
category204 = Category.create(name: 'Interstage WEBCOORDINATOR')
category205 = Category.create(name: 'Interstage Charset Manager')
category206 = Category.create(name: 'Interstage Print Manager')
category207 = Category.create(name: 'Interstage ApCoordinator')
category208 = Category.create(name: 'Interstage Application Server')
category209 = Category.create(name: 'Interstage EnterpriseEdition')
category210 = Category.create(name: 'Interstage Collaboration Ring')
category211 = Category.create(name: 'Interstage Traffic Director')
category212 = Category.create(name: 'Interstage PortalWorks')
category213 = Category.create(name: 'Interstage ContentBiz')
category214 = Category.create(name: 'Interstage Knowledge Server')
category215 = Category.create(name: 'Interstage Realtime Communitator')
category216 = Category.create(name: 'Interstage Data Collector')
category217 = Category.create(name: 'Interstage Web-J Edition')
category218 = Category.create(name: 'Sun One Application Server')
category219 = Category.create(name: 'Netscape Application Server')
category220 = Category.create(name: 'Oracle Application Server')
category221 = Category.create(name: 'WebSphere Application Server')
category222 = Category.create(name: 'WebLogic Server')
category223 = Category.create(name: 'Tomcat')
category224 = Category.create(name: 'Apache')
category225 = Category.create(name: 'JBOSS')
category226 = Category.create(name: 'InfoProviderPro')
category227 = Category.create(name: 'NetscapeCommunicationsServer')
category228 = Category.create(name: 'IIS')
category229 = Category.create(name: 'Sun One Web Server')
category230 = Category.create(name: 'Oracle Web Server')
category231 = Category.create(name: 'NetWare Web Server/InternetWare')
category232 = Category.create(name: 'Internet Connection Server')
category233 = Category.create(name: 'Netscape Enterprise Server')
category234 = Category.create(name: 'Webサーバその他')
category235 = Category.create(name: 'Topjax')
category236 = Category.create(name: 'EZDeveroper')
category237 = Category.create(name: 'Struts')
category238 = Category.create(name: 'Autodesk DWFWriter')
category239 = Category.create(name: 'ICAD/SX Mechanical PRO')
category240 = Category.create(name: 'KDraster')
category241 = Category.create(name: 'その他CAD/イメージ関連ツール')
category242 = Category.create(name: 'Geobase')
category243 = Category.create(name: 'ChartRescue')
category244 = Category.create(name: 'その他GIS関連ツール')
category245 = Category.create(name: '映像配信')
category246 = Category.create(name: 'その他開発ツール')
category247 = Category.create(name: '公開鍵暗号方式')
category248 = Category.create(name: '秘密鍵暗号方式')
category249 = Category.create(name: 'SSL')
category250 = Category.create(name: '認証局')
category251 = Category.create(name: '電子署名')
category252 = Category.create(name: 'TCG')
category253 = Category.create(name: 'FireWall-1')
category254 = Category.create(name: 'Safegate')
category255 = Category.create(name: 'NetShelter')
category256 = Category.create(name: 'ファイアウォールその他')
category257 = Category.create(name: 'InfoProxy')
category258 = Category.create(name: 'Netscape Certificate Server')
category259 = Category.create(name: 'Netscape Directory Server')
category260 = Category.create(name: 'Microsoft Certificate Server')
category261 = Category.create(name: 'Securecryptoライブラリ')
category262 = Category.create(name: 'Secure PC Card')
category263 = Category.create(name: 'SecureID')
category264 = Category.create(name: 'スマート認証')
category265 = Category.create(name: 'Fingsensor')
category266 = Category.create(name: 'SuperSIGN')
category267 = Category.create(name: 'SECUREACH')
category268 = Category.create(name: 'GLOVIA')
category269 = Category.create(name: 'GLOVIA-C')
category270 = Category.create(name: 'SAPR/3')
category271 = Category.create(name: 'Oracle Applications')
category272 = Category.create(name: 'BAAN')
category273 = Category.create(name: 'JD Edwards')
category274 = Category.create(name: 'People Soft')
category275 = Category.create(name: 'SSJ SupertStream')
category276 = Category.create(name: 'SCAW')
category277 = Category.create(name: '統合業務パッケージその他')
category278 = Category.create(name: 'GLOVIA-PUBLIC')
category279 = Category.create(name: 'IPK')
category280 = Category.create(name: 'ATMSシリーズ')
category281 = Category.create(name: '司シリーズ')
category282 = Category.create(name: 'InternetNavigware')
category283 = Category.create(name: 'TeamWARE Office')
category284 = Category.create(name: 'TeamWARE Flow')
category285 = Category.create(name: 'TeamWARE')
category286 = Category.create(name: 'Notes/Domino')
category287 = Category.create(name: 'GroupWise')
category288 = Category.create(name: 'Exchange')
category289 = Category.create(name: 'Groupmax')
category290 = Category.create(name: 'StarOffice')
category291 = Category.create(name: 'サイボウズOffice')
category292 = Category.create(name: 'Oracle InterOffice')
category293 = Category.create(name: 'Netscape Communicator(Collabra)')
category294 = Category.create(name: 'MyOFFICE')
category295 = Category.create(name: 'CHOKOA')
category296 = Category.create(name: 'SystemWalker/CentricManager')
category297 = Category.create(name: 'SystemWalker/NetPrism')
category298 = Category.create(name: 'SystemWalker/OperationManager')
category299 = Category.create(name: 'SystemWalker/ParallelWORKS')
category300 = Category.create(name: 'SystemWalker/IP Ner MGR')
category301 = Category.create(name: 'SystemWalker/PerfMGR(性能管理)')
category302 = Category.create(name: 'SystemWalker/WebMGR')
category303 = Category.create(name: 'SystemWalker/TrendView')
category304 = Category.create(name: 'SystemWalker for Oracle')
category305 = Category.create(name: 'SystemWalker for Notes/Domino')
category306 = Category.create(name: 'SystemWalker for R/3')
category307 = Category.create(name: 'SystemWalker for TP')
category308 = Category.create(name: 'SystemWalker for SymfoWARE')
category309 = Category.create(name: 'SystemWalker/ListWORKS(帳票管理)')
category310 = Category.create(name: 'SystemWalker/PrintMGR(印刷管理)')
category311 = Category.create(name: 'SystemWalker/StorageMGR')
category312 = Category.create(name: 'SystemWalker/IT BudgetMGR')
category313 = Category.create(name: 'SystemWalker/UserAccessMGR')
category314 = Category.create(name: 'SystemWalker/getAccess')
category315 = Category.create(name: 'SystemWalker/SoftDelivery')
category316 = Category.create(name: 'SystemWalker/Resource Coordinator')
category317 = Category.create(name: 'SystemWalker/Service Quality Coordinator')
category318 = Category.create(name: 'SystemWalker/SelfHealing')
category319 = Category.create(name: 'SystemWalker/FINALDATA')
category320 = Category.create(name: 'SystemWalker/Network Topology Manager')
category321 = Category.create(name: 'SystemWalker/Network Assist')
category322 = Category.create(name: 'SystemWalker IT/AssetMGR')
category323 = Category.create(name: 'SystemWalker/Desktop Patorol')
category324 = Category.create(name: 'SystemWalker/Desktop Monitor')
category325 = Category.create(name: 'SystemWalker/InfoDirectory')
category326 = Category.create(name: 'SystemWalker/PkiMGR')
category327 = Category.create(name: 'SystemWalker/Event Agent')
category328 = Category.create(name: 'SystemWalker/Live Help')
category329 = Category.create(name: 'SystemWalkerその他')
category330 = Category.create(name: 'ARCserve')
category331 = Category.create(name: 'NetWorker')
category332 = Category.create(name: 'Oracle Recovery Manager')
category333 = Category.create(name: 'SymfoNET')
category334 = Category.create(name: 'SMS')
category335 = Category.create(name: 'TME(Tivoli)')
category336 = Category.create(name: 'OpenView')
category337 = Category.create(name: 'CA-Univenter')
category338 = Category.create(name: 'Solstice')
category339 = Category.create(name: 'NetView')
category340 = Category.create(name: 'ManageWise')
category341 = Category.create(name: 'ZAK(ZeroAdministrationKit)')
category342 = Category.create(name: 'NetValue')
category343 = Category.create(name: '資産/保守管理その他')
category344 = Category.create(name: 'CTI')
category345 = Category.create(name: 'コールセンター')
category346 = Category.create(name: 'ヘルプデスク')

Layer.create(category1_id: category1.id, category2_id: category12.id)
Layer.create(category1_id: category11.id, category2_id: category13.id)
Layer.create(category1_id: category11.id, category2_id: category14.id)
Layer.create(category1_id: category11.id, category2_id: category15.id)
Layer.create(category1_id: category11.id, category2_id: category16.id)
Layer.create(category1_id: category11.id, category2_id: category17.id)
Layer.create(category1_id: category11.id, category2_id: category18.id)
Layer.create(category1_id: category11.id, category2_id: category19.id)
Layer.create(category1_id: category11.id, category2_id: category20.id)
Layer.create(category1_id: category11.id, category2_id: category21.id)
Layer.create(category1_id: category11.id, category2_id: category22.id)
Layer.create(category1_id: category11.id, category2_id: category23.id)
Layer.create(category1_id: category11.id, category2_id: category24.id)
Layer.create(category1_id: category11.id, category2_id: category25.id)
Layer.create(category1_id: category11.id, category2_id: category26.id)
Layer.create(category1_id: category11.id, category2_id: category27.id)
Layer.create(category1_id: category11.id, category2_id: category28.id)
Layer.create(category1_id: category11.id, category2_id: category29.id)
Layer.create(category1_id: category11.id, category2_id: category30.id)
Layer.create(category1_id: category11.id, category2_id: category31.id)
Layer.create(category1_id: category11.id, category2_id: category32.id)
Layer.create(category1_id: category11.id, category2_id: category33.id)
Layer.create(category1_id: category11.id, category2_id: category34.id)
Layer.create(category1_id: category11.id, category2_id: category35.id)
Layer.create(category1_id: category11.id, category2_id: category36.id)
Layer.create(category1_id: category11.id, category2_id: category37.id)
Layer.create(category1_id: category11.id, category2_id: category38.id)
Layer.create(category1_id: category11.id, category2_id: category39.id)
Layer.create(category1_id: category2.id, category2_id: category40.id)
Layer.create(category1_id: category11.id, category2_id: category41.id)
Layer.create(category1_id: category11.id, category2_id: category42.id)
Layer.create(category1_id: category11.id, category2_id: category43.id)
Layer.create(category1_id: category11.id, category2_id: category44.id)
Layer.create(category1_id: category11.id, category2_id: category45.id)
Layer.create(category1_id: category11.id, category2_id: category46.id)
Layer.create(category1_id: category11.id, category2_id: category47.id)
Layer.create(category1_id: category11.id, category2_id: category48.id)
Layer.create(category1_id: category11.id, category2_id: category49.id)
Layer.create(category1_id: category11.id, category2_id: category50.id)
Layer.create(category1_id: category11.id, category2_id: category51.id)
Layer.create(category1_id: category11.id, category2_id: category52.id)
Layer.create(category1_id: category11.id, category2_id: category53.id)
Layer.create(category1_id: category11.id, category2_id: category54.id)
Layer.create(category1_id: category11.id, category2_id: category55.id)
Layer.create(category1_id: category11.id, category2_id: category56.id)
Layer.create(category1_id: category11.id, category2_id: category57.id)
Layer.create(category1_id: category11.id, category2_id: category58.id)
Layer.create(category1_id: category11.id, category2_id: category59.id)
Layer.create(category1_id: category11.id, category2_id: category60.id)
Layer.create(category1_id: category11.id, category2_id: category61.id)
Layer.create(category1_id: category11.id, category2_id: category62.id)
Layer.create(category1_id: category11.id, category2_id: category63.id)
Layer.create(category1_id: category11.id, category2_id: category64.id)
Layer.create(category1_id: category11.id, category2_id: category65.id)
Layer.create(category1_id: category11.id, category2_id: category66.id)
Layer.create(category1_id: category11.id, category2_id: category67.id)
Layer.create(category1_id: category11.id, category2_id: category68.id)
Layer.create(category1_id: category11.id, category2_id: category69.id)
Layer.create(category1_id: category11.id, category2_id: category70.id)
Layer.create(category1_id: category11.id, category2_id: category71.id)
Layer.create(category1_id: category11.id, category2_id: category72.id)
Layer.create(category1_id: category11.id, category2_id: category73.id)
Layer.create(category1_id: category11.id, category2_id: category74.id)
Layer.create(category1_id: category11.id, category2_id: category75.id)
Layer.create(category1_id: category11.id, category2_id: category76.id)
Layer.create(category1_id: category11.id, category2_id: category77.id)
Layer.create(category1_id: category11.id, category2_id: category78.id)
Layer.create(category1_id: category11.id, category2_id: category79.id)
Layer.create(category1_id: category11.id, category2_id: category80.id)
Layer.create(category1_id: category11.id, category2_id: category81.id)
Layer.create(category1_id: category11.id, category2_id: category82.id)
Layer.create(category1_id: category11.id, category2_id: category83.id)
Layer.create(category1_id: category11.id, category2_id: category84.id)
Layer.create(category1_id: category11.id, category2_id: category85.id)
Layer.create(category1_id: category3.id, category2_id: category86.id)
Layer.create(category1_id: category11.id, category2_id: category87.id)
Layer.create(category1_id: category11.id, category2_id: category88.id)
Layer.create(category1_id: category11.id, category2_id: category89.id)
Layer.create(category1_id: category11.id, category2_id: category90.id)
Layer.create(category1_id: category11.id, category2_id: category91.id)
Layer.create(category1_id: category11.id, category2_id: category92.id)
Layer.create(category1_id: category11.id, category2_id: category93.id)
Layer.create(category1_id: category11.id, category2_id: category94.id)
Layer.create(category1_id: category11.id, category2_id: category95.id)
Layer.create(category1_id: category11.id, category2_id: category96.id)
Layer.create(category1_id: category11.id, category2_id: category97.id)
Layer.create(category1_id: category11.id, category2_id: category98.id)
Layer.create(category1_id: category11.id, category2_id: category99.id)
Layer.create(category1_id: category11.id, category2_id: category100.id)
Layer.create(category1_id: category11.id, category2_id: category101.id)
Layer.create(category1_id: category11.id, category2_id: category102.id)
Layer.create(category1_id: category11.id, category2_id: category103.id)
Layer.create(category1_id: category11.id, category2_id: category104.id)
Layer.create(category1_id: category11.id, category2_id: category105.id)
Layer.create(category1_id: category11.id, category2_id: category106.id)
Layer.create(category1_id: category11.id, category2_id: category107.id)
Layer.create(category1_id: category11.id, category2_id: category108.id)
Layer.create(category1_id: category11.id, category2_id: category109.id)
Layer.create(category1_id: category11.id, category2_id: category110.id)
Layer.create(category1_id: category4.id, category2_id: category111.id)
Layer.create(category1_id: category11.id, category2_id: category112.id)
Layer.create(category1_id: category11.id, category2_id: category113.id)
Layer.create(category1_id: category11.id, category2_id: category114.id )
Layer.create(category1_id: category11.id, category2_id: category115.id)
Layer.create(category1_id: category11.id, category2_id: category116.id)
Layer.create(category1_id: category11.id, category2_id: category117.id)
Layer.create(category1_id: category11.id, category2_id: category118.id)
Layer.create(category1_id: category11.id, category2_id: category119.id)
Layer.create(category1_id: category11.id, category2_id: category120.id)
Layer.create(category1_id: category11.id, category2_id: category121.id)
Layer.create(category1_id: category11.id, category2_id: category122.id)
Layer.create(category1_id: category11.id, category2_id: category123.id)
Layer.create(category1_id: category11.id, category2_id: category124.id)
Layer.create(category1_id: category11.id, category2_id: category125.id)
Layer.create(category1_id: category11.id, category2_id: category126.id)
Layer.create(category1_id: category11.id, category2_id: category127.id)
Layer.create(category1_id: category11.id, category2_id: category128.id)
Layer.create(category1_id: category11.id, category2_id: category129.id)
Layer.create(category1_id: category11.id, category2_id: category130.id)
Layer.create(category1_id: category11.id, category2_id: category131.id)
Layer.create(category1_id: category11.id, category2_id: category132.id)
Layer.create(category1_id: category11.id, category2_id: category133.id)
Layer.create(category1_id: category11.id, category2_id: category134.id)
Layer.create(category1_id: category11.id, category2_id: category135.id)
Layer.create(category1_id: category11.id, category2_id: category136.id)
Layer.create(category1_id: category11.id, category2_id: category137.id)
Layer.create(category1_id: category11.id, category2_id: category138.id)
Layer.create(category1_id: category11.id, category2_id: category139.id)
Layer.create(category1_id: category11.id, category2_id: category140.id)
Layer.create(category1_id: category11.id, category2_id: category141.id)
Layer.create(category1_id: category11.id, category2_id: category142.id)
Layer.create(category1_id: category11.id, category2_id: category143.id)
Layer.create(category1_id: category11.id, category2_id: category144.id)
Layer.create(category1_id: category11.id, category2_id: category145.id)
Layer.create(category1_id: category11.id, category2_id: category146.id)
Layer.create(category1_id: category11.id, category2_id: category147.id)
Layer.create(category1_id: category11.id, category2_id: category148.id)
Layer.create(category1_id: category11.id, category2_id: category149.id)
Layer.create(category1_id: category11.id, category2_id: category150.id)
Layer.create(category1_id: category5.id, category2_id: category151.id)
Layer.create(category1_id: category11.id, category2_id: category152.id)
Layer.create(category1_id: category11.id, category2_id: category153.id)
Layer.create(category1_id: category11.id, category2_id: category154.id)
Layer.create(category1_id: category11.id, category2_id: category155.id)
Layer.create(category1_id: category11.id, category2_id: category156.id)
Layer.create(category1_id: category11.id, category2_id: category157.id)
Layer.create(category1_id: category11.id, category2_id: category158.id)
Layer.create(category1_id: category11.id, category2_id: category159.id)
Layer.create(category1_id: category6.id, category2_id: category160.id)
Layer.create(category1_id: category11.id, category2_id: category161.id)
Layer.create(category1_id: category11.id, category2_id: category162.id)
Layer.create(category1_id: category11.id, category2_id: category163.id)
Layer.create(category1_id: category11.id, category2_id: category164.id)
Layer.create(category1_id: category11.id, category2_id: category165.id)
Layer.create(category1_id: category11.id, category2_id: category166.id)
Layer.create(category1_id: category11.id, category2_id: category167.id)
Layer.create(category1_id: category11.id, category2_id: category168.id)
Layer.create(category1_id: category11.id, category2_id: category169.id)
Layer.create(category1_id: category11.id, category2_id: category170.id)
Layer.create(category1_id: category11.id, category2_id: category171.id)
Layer.create(category1_id: category11.id, category2_id: category172.id)
Layer.create(category1_id: category11.id, category2_id: category173.id)
Layer.create(category1_id: category11.id, category2_id: category174.id)
Layer.create(category1_id: category11.id, category2_id: category175.id)
Layer.create(category1_id: category11.id, category2_id: category176.id)
Layer.create(category1_id: category11.id, category2_id: category177.id)
Layer.create(category1_id: category11.id, category2_id: category178.id)
Layer.create(category1_id: category11.id, category2_id: category179.id)
Layer.create(category1_id: category11.id, category2_id: category180.id)
Layer.create(category1_id: category11.id, category2_id: category181.id)
Layer.create(category1_id: category11.id, category2_id: category182.id)
Layer.create(category1_id: category11.id, category2_id: category183.id)
Layer.create(category1_id: category11.id, category2_id: category184.id)
Layer.create(category1_id: category11.id, category2_id: category185.id)
Layer.create(category1_id: category11.id, category2_id: category186.id)
Layer.create(category1_id: category11.id, category2_id: category187.id)
Layer.create(category1_id: category11.id, category2_id: category188.id)
Layer.create(category1_id: category11.id, category2_id: category189.id)
Layer.create(category1_id: category11.id, category2_id: category190.id)
Layer.create(category1_id: category11.id, category2_id: category191.id)
Layer.create(category1_id: category11.id, category2_id: category192.id)
Layer.create(category1_id: category11.id, category2_id: category193.id)
Layer.create(category1_id: category11.id, category2_id: category194.id)
Layer.create(category1_id: category11.id, category2_id: category195.id)
Layer.create(category1_id: category11.id, category2_id: category196.id)
Layer.create(category1_id: category11.id, category2_id: category197.id)
Layer.create(category1_id: category11.id, category2_id: category198.id)
Layer.create(category1_id: category11.id, category2_id: category199.id)
Layer.create(category1_id: category11.id, category2_id: category200.id)
Layer.create(category1_id: category11.id, category2_id: category201.id)
Layer.create(category1_id: category11.id, category2_id: category202.id)
Layer.create(category1_id: category11.id, category2_id: category203.id)
Layer.create(category1_id: category11.id, category2_id: category204.id)
Layer.create(category1_id: category11.id, category2_id: category205.id)
Layer.create(category1_id: category11.id, category2_id: category206.id)
Layer.create(category1_id: category11.id, category2_id: category207.id)
Layer.create(category1_id: category11.id, category2_id: category208.id)
Layer.create(category1_id: category11.id, category2_id: category209.id)
Layer.create(category1_id: category11.id, category2_id: category210.id)
Layer.create(category1_id: category11.id, category2_id: category211.id)
Layer.create(category1_id: category11.id, category2_id: category212.id)
Layer.create(category1_id: category11.id, category2_id: category213.id)
Layer.create(category1_id: category11.id, category2_id: category214.id)
Layer.create(category1_id: category11.id, category2_id: category215.id)
Layer.create(category1_id: category11.id, category2_id: category216.id)
Layer.create(category1_id: category11.id, category2_id: category217.id)
Layer.create(category1_id: category11.id, category2_id: category218.id)
Layer.create(category1_id: category11.id, category2_id: category219.id)
Layer.create(category1_id: category11.id, category2_id: category220.id)
Layer.create(category1_id: category11.id, category2_id: category221.id)
Layer.create(category1_id: category11.id, category2_id: category222.id)
Layer.create(category1_id: category11.id, category2_id: category223.id)
Layer.create(category1_id: category11.id, category2_id: category224.id)
Layer.create(category1_id: category11.id, category2_id: category225.id)
Layer.create(category1_id: category11.id, category2_id: category226.id)
Layer.create(category1_id: category11.id, category2_id: category227.id)
Layer.create(category1_id: category11.id, category2_id: category228.id)
Layer.create(category1_id: category11.id, category2_id: category229.id)
Layer.create(category1_id: category11.id, category2_id: category230.id)
Layer.create(category1_id: category11.id, category2_id: category231.id)
Layer.create(category1_id: category11.id, category2_id: category232.id)
Layer.create(category1_id: category11.id, category2_id: category233.id)
Layer.create(category1_id: category11.id, category2_id: category234.id)
Layer.create(category1_id: category11.id, category2_id: category235.id)
Layer.create(category1_id: category11.id, category2_id: category236.id)
Layer.create(category1_id: category11.id, category2_id: category237.id)
Layer.create(category1_id: category11.id, category2_id: category238.id)
Layer.create(category1_id: category11.id, category2_id: category239.id)
Layer.create(category1_id: category11.id, category2_id: category240.id)
Layer.create(category1_id: category11.id, category2_id: category241.id)
Layer.create(category1_id: category11.id, category2_id: category242.id)
Layer.create(category1_id: category11.id, category2_id: category243.id)
Layer.create(category1_id: category11.id, category2_id: category244.id)
Layer.create(category1_id: category11.id, category2_id: category245.id)
Layer.create(category1_id: category11.id, category2_id: category246.id)
Layer.create(category1_id: category7.id, category2_id: category247.id)
Layer.create(category1_id: category11.id, category2_id: category248.id)
Layer.create(category1_id: category11.id, category2_id: category249.id)
Layer.create(category1_id: category11.id, category2_id: category250.id)
Layer.create(category1_id: category11.id, category2_id: category251.id)
Layer.create(category1_id: category11.id, category2_id: category252.id)
Layer.create(category1_id: category11.id, category2_id: category253.id)
Layer.create(category1_id: category11.id, category2_id: category254.id)
Layer.create(category1_id: category11.id, category2_id: category255.id)
Layer.create(category1_id: category11.id, category2_id: category256.id)
Layer.create(category1_id: category11.id, category2_id: category257.id)
Layer.create(category1_id: category11.id, category2_id: category258.id)
Layer.create(category1_id: category11.id, category2_id: category259.id)
Layer.create(category1_id: category11.id, category2_id: category260.id)
Layer.create(category1_id: category11.id, category2_id: category261.id)
Layer.create(category1_id: category11.id, category2_id: category262.id)
Layer.create(category1_id: category11.id, category2_id: category263.id)
Layer.create(category1_id: category11.id, category2_id: category264.id)
Layer.create(category1_id: category11.id, category2_id: category265.id)
Layer.create(category1_id: category11.id, category2_id: category266.id)
Layer.create(category1_id: category11.id, category2_id: category267.id)
Layer.create(category1_id: category8.id, category2_id: category268.id)
Layer.create(category1_id: category11.id, category2_id: category269.id)
Layer.create(category1_id: category11.id, category2_id: category270.id)
Layer.create(category1_id: category11.id, category2_id: category271.id)
Layer.create(category1_id: category11.id, category2_id: category272.id)
Layer.create(category1_id: category11.id, category2_id: category273.id)
Layer.create(category1_id: category11.id, category2_id: category274.id)
Layer.create(category1_id: category11.id, category2_id: category275.id)
Layer.create(category1_id: category11.id, category2_id: category276.id)
Layer.create(category1_id: category11.id, category2_id: category277.id)
Layer.create(category1_id: category11.id, category2_id: category278.id)
Layer.create(category1_id: category11.id, category2_id: category279.id)
Layer.create(category1_id: category11.id, category2_id: category280.id)
Layer.create(category1_id: category11.id, category2_id: category281.id)
Layer.create(category1_id: category11.id, category2_id: category282.id)
Layer.create(category1_id: category9.id, category2_id: category283.id)
Layer.create(category1_id: category11.id, category2_id: category284.id)
Layer.create(category1_id: category11.id, category2_id: category285.id)
Layer.create(category1_id: category11.id, category2_id: category286.id)
Layer.create(category1_id: category11.id, category2_id: category287.id)
Layer.create(category1_id: category11.id, category2_id: category288.id)
Layer.create(category1_id: category11.id, category2_id: category289.id)
Layer.create(category1_id: category11.id, category2_id: category290.id)
Layer.create(category1_id: category11.id, category2_id: category291.id)
Layer.create(category1_id: category11.id, category2_id: category292.id)
Layer.create(category1_id: category11.id, category2_id: category293.id)
Layer.create(category1_id: category11.id, category2_id: category294.id)
Layer.create(category1_id: category11.id, category2_id: category295.id)
Layer.create(category1_id: category10.id, category2_id: category296.id)
Layer.create(category1_id: category11.id, category2_id: category297.id)
Layer.create(category1_id: category11.id, category2_id: category298.id)
Layer.create(category1_id: category11.id, category2_id: category299.id)
Layer.create(category1_id: category11.id, category2_id: category300.id)
Layer.create(category1_id: category11.id, category2_id: category301.id)
Layer.create(category1_id: category11.id, category2_id: category302.id)
Layer.create(category1_id: category11.id, category2_id: category303.id)
Layer.create(category1_id: category11.id, category2_id: category304.id)
Layer.create(category1_id: category11.id, category2_id: category305.id)
Layer.create(category1_id: category11.id, category2_id: category306.id)
Layer.create(category1_id: category11.id, category2_id: category307.id)
Layer.create(category1_id: category11.id, category2_id: category308.id)
Layer.create(category1_id: category11.id, category2_id: category309.id)
Layer.create(category1_id: category11.id, category2_id: category310.id)
Layer.create(category1_id: category11.id, category2_id: category311.id)
Layer.create(category1_id: category11.id, category2_id: category312.id)
Layer.create(category1_id: category11.id, category2_id: category313.id)
Layer.create(category1_id: category11.id, category2_id: category314.id)
Layer.create(category1_id: category11.id, category2_id: category315.id)
Layer.create(category1_id: category11.id, category2_id: category316.id)
Layer.create(category1_id: category11.id, category2_id: category317.id)
Layer.create(category1_id: category11.id, category2_id: category318.id)
Layer.create(category1_id: category11.id, category2_id: category319.id)
Layer.create(category1_id: category11.id, category2_id: category320.id)
Layer.create(category1_id: category11.id, category2_id: category321.id)
Layer.create(category1_id: category11.id, category2_id: category322.id)
Layer.create(category1_id: category11.id, category2_id: category323.id)
Layer.create(category1_id: category11.id, category2_id: category324.id)
Layer.create(category1_id: category11.id, category2_id: category325.id)
Layer.create(category1_id: category11.id, category2_id: category326.id)
Layer.create(category1_id: category11.id, category2_id: category327.id)
Layer.create(category1_id: category11.id, category2_id: category328.id)
Layer.create(category1_id: category11.id, category2_id: category329.id)
Layer.create(category1_id: category11.id, category2_id: category330.id)
Layer.create(category1_id: category11.id, category2_id: category331.id)
Layer.create(category1_id: category11.id, category2_id: category332.id)
Layer.create(category1_id: category11.id, category2_id: category333.id)
Layer.create(category1_id: category11.id, category2_id: category334.id)
Layer.create(category1_id: category11.id, category2_id: category335.id)
Layer.create(category1_id: category11.id, category2_id: category336.id)
Layer.create(category1_id: category11.id, category2_id: category337.id)
Layer.create(category1_id: category11.id, category2_id: category338.id)
Layer.create(category1_id: category11.id, category2_id: category339.id)
Layer.create(category1_id: category11.id, category2_id: category340.id)
Layer.create(category1_id: category11.id, category2_id: category341.id)
Layer.create(category1_id: category11.id, category2_id: category342.id)
Layer.create(category1_id: category11.id, category2_id: category343.id)
Layer.create(category1_id: category11.id, category2_id: category344.id)
Layer.create(category1_id: category11.id, category2_id: category345.id)
Layer.create(category1_id: category11.id, category2_id: category346.id)

User.create(login: 'admin', email: 'admin1@sample.com', username: 'admin', password: 'password', admin: true)
User.create(login: 'hara-t', email: 'hara-t@i-sol.jp', username: '原隆行', password: 'password', admin: false)
User.create(login: 'imajyo-t', email: 'imajyo-t@i-sol.jp', username: '今城建', password: 'password', admin: false)
User.create(login: 'kurata-t', email: 'kurata-t@i-sol.jp', username: '倉田朋幸', password: 'password', admin: false)
User.create(login: 'murakami-f', email: 'murakami-f@i-sol.jp', username: '村上史恵', password: 'password', admin: false)
User.create(login: 'megumi-s', email: 'megumi-s@i-sol.jp', username: '恵聡', password: 'password', admin: false)
User.create(login: 'horikawa-m', email: 'horikawa-m@i-sol.jp', username: '堀川美咲', password: 'password', admin: false)
User.create(login: 'suzuki-a', email: 'suzuki-a@i-sol.jp', username: '鈴木亜理沙', password: 'password', admin: false)
User.create(login: 'ito-m', email: 'ito-m@i-sol.jp', username: '伊藤真唯美', password: 'password', admin: false)
User.create(login: 'hayashi-k', email: 'hayashi-k@i-sol.jp', username: '林克明', password: 'password', admin: false)
User.create(login: 'You-s', email: 'You-s@i-sol.jp', username: '楊笑天', password: 'password', admin: false)
User.create(login: 'tomiyama-h', email: 'tomiyama-h@i-sol.jp', username: '富山秀成', password: 'password', admin: false)
User.create(login: 'ozaki-s', email: 'ozaki-s@i-sol.jp', username: '尾崎秀太', password: 'password', admin: false)
User.create(login: 'kobayashi-n', email: 'kobayashi-n@i-sol.jp', username: '小林信慶', password: 'password', admin: false)
User.create(login: 'Yamamoto-k2', email: 'Yamamoto-k2@i-sol.jp', username: '山本幸介', password: 'password', admin: false)
User.create(login: 'sato-k', email: 'sato-k@i-sol.jp', username: '佐藤恵太', password: 'password', admin: false)
User.create(login: 'ka-gyokukai', email: 'ka-gyokukai@i-sol.jp', username: '何玉海', password: 'password', admin: false)
User.create(login: 'Syu-s', email: 'Syu-s@i-sol.jp', username: '周鑫', password: 'password', admin: false)
User.create(login: 'debnath-s', email: 'debnath-s@i-sol.jp', username: 'デブナトサンタヌ', password: 'password', admin: false)
User.create(login: 'sakurai-n', email: 'sakurai-n@i-sol.jp', username: '櫻井七海', password: 'password', admin: false)